//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Communication.CompanyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        private Company.Communication.CompanyService.Department DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Company.Communication.CompanyService.Department Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((this.DepartmentField.Equals(value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    public enum Department : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sales = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Purchasing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Service = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.CompanyServiceSoap")]
    public interface CompanyServiceSoap {
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        Company.Communication.CompanyService.AddResponse Add(Company.Communication.CompanyService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<Company.Communication.CompanyService.AddResponse> AddAsync(Company.Communication.CompanyService.AddRequest request);
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        Company.Communication.CompanyService.RemoveResponse Remove(Company.Communication.CompanyService.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        System.Threading.Tasks.Task<Company.Communication.CompanyService.RemoveResponse> RemoveAsync(Company.Communication.CompanyService.RemoveRequest request);
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        Company.Communication.CompanyService.UpdateResponse Update(Company.Communication.CompanyService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Company.Communication.CompanyService.UpdateResponse> UpdateAsync(Company.Communication.CompanyService.UpdateRequest request);
        
        // CODEGEN: Generating message contract since element name LoadResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Load", ReplyAction="*")]
        Company.Communication.CompanyService.LoadResponse Load(Company.Communication.CompanyService.LoadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Load", ReplyAction="*")]
        System.Threading.Tasks.Task<Company.Communication.CompanyService.LoadResponse> LoadAsync(Company.Communication.CompanyService.LoadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public Company.Communication.CompanyService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(Company.Communication.CompanyService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Company.Communication.CompanyService.Employee employee;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(Company.Communication.CompanyService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public Company.Communication.CompanyService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(Company.Communication.CompanyService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(int AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://tempuri.org/", Order=0)]
        public Company.Communication.CompanyService.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(Company.Communication.CompanyService.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Company.Communication.CompanyService.Employee employee;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(Company.Communication.CompanyService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Company.Communication.CompanyService.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(Company.Communication.CompanyService.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(int RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public Company.Communication.CompanyService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Company.Communication.CompanyService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Company.Communication.CompanyService.Employee employee;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(Company.Communication.CompanyService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Company.Communication.CompanyService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(Company.Communication.CompanyService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(int UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Load", Namespace="http://tempuri.org/", Order=0)]
        public Company.Communication.CompanyService.LoadRequestBody Body;
        
        public LoadRequest() {
        }
        
        public LoadRequest(Company.Communication.CompanyService.LoadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadRequestBody {
        
        public LoadRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadResponse", Namespace="http://tempuri.org/", Order=0)]
        public Company.Communication.CompanyService.LoadResponseBody Body;
        
        public LoadResponse() {
        }
        
        public LoadResponse(Company.Communication.CompanyService.LoadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Company.Communication.CompanyService.Employee[] LoadResult;
        
        public LoadResponseBody() {
        }
        
        public LoadResponseBody(Company.Communication.CompanyService.Employee[] LoadResult) {
            this.LoadResult = LoadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompanyServiceSoapChannel : Company.Communication.CompanyService.CompanyServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyServiceSoapClient : System.ServiceModel.ClientBase<Company.Communication.CompanyService.CompanyServiceSoap>, Company.Communication.CompanyService.CompanyServiceSoap {
        
        public CompanyServiceSoapClient() {
        }
        
        public CompanyServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Company.Communication.CompanyService.AddResponse Company.Communication.CompanyService.CompanyServiceSoap.Add(Company.Communication.CompanyService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public int Add(Company.Communication.CompanyService.Employee employee) {
            Company.Communication.CompanyService.AddRequest inValue = new Company.Communication.CompanyService.AddRequest();
            inValue.Body = new Company.Communication.CompanyService.AddRequestBody();
            inValue.Body.employee = employee;
            Company.Communication.CompanyService.AddResponse retVal = ((Company.Communication.CompanyService.CompanyServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Company.Communication.CompanyService.AddResponse> Company.Communication.CompanyService.CompanyServiceSoap.AddAsync(Company.Communication.CompanyService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Company.Communication.CompanyService.AddResponse> AddAsync(Company.Communication.CompanyService.Employee employee) {
            Company.Communication.CompanyService.AddRequest inValue = new Company.Communication.CompanyService.AddRequest();
            inValue.Body = new Company.Communication.CompanyService.AddRequestBody();
            inValue.Body.employee = employee;
            return ((Company.Communication.CompanyService.CompanyServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Company.Communication.CompanyService.RemoveResponse Company.Communication.CompanyService.CompanyServiceSoap.Remove(Company.Communication.CompanyService.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public int Remove(Company.Communication.CompanyService.Employee employee) {
            Company.Communication.CompanyService.RemoveRequest inValue = new Company.Communication.CompanyService.RemoveRequest();
            inValue.Body = new Company.Communication.CompanyService.RemoveRequestBody();
            inValue.Body.employee = employee;
            Company.Communication.CompanyService.RemoveResponse retVal = ((Company.Communication.CompanyService.CompanyServiceSoap)(this)).Remove(inValue);
            return retVal.Body.RemoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Company.Communication.CompanyService.RemoveResponse> Company.Communication.CompanyService.CompanyServiceSoap.RemoveAsync(Company.Communication.CompanyService.RemoveRequest request) {
            return base.Channel.RemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Company.Communication.CompanyService.RemoveResponse> RemoveAsync(Company.Communication.CompanyService.Employee employee) {
            Company.Communication.CompanyService.RemoveRequest inValue = new Company.Communication.CompanyService.RemoveRequest();
            inValue.Body = new Company.Communication.CompanyService.RemoveRequestBody();
            inValue.Body.employee = employee;
            return ((Company.Communication.CompanyService.CompanyServiceSoap)(this)).RemoveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Company.Communication.CompanyService.UpdateResponse Company.Communication.CompanyService.CompanyServiceSoap.Update(Company.Communication.CompanyService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public int Update(Company.Communication.CompanyService.Employee employee) {
            Company.Communication.CompanyService.UpdateRequest inValue = new Company.Communication.CompanyService.UpdateRequest();
            inValue.Body = new Company.Communication.CompanyService.UpdateRequestBody();
            inValue.Body.employee = employee;
            Company.Communication.CompanyService.UpdateResponse retVal = ((Company.Communication.CompanyService.CompanyServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Company.Communication.CompanyService.UpdateResponse> Company.Communication.CompanyService.CompanyServiceSoap.UpdateAsync(Company.Communication.CompanyService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Company.Communication.CompanyService.UpdateResponse> UpdateAsync(Company.Communication.CompanyService.Employee employee) {
            Company.Communication.CompanyService.UpdateRequest inValue = new Company.Communication.CompanyService.UpdateRequest();
            inValue.Body = new Company.Communication.CompanyService.UpdateRequestBody();
            inValue.Body.employee = employee;
            return ((Company.Communication.CompanyService.CompanyServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Company.Communication.CompanyService.LoadResponse Company.Communication.CompanyService.CompanyServiceSoap.Load(Company.Communication.CompanyService.LoadRequest request) {
            return base.Channel.Load(request);
        }
        
        public Company.Communication.CompanyService.Employee[] Load() {
            Company.Communication.CompanyService.LoadRequest inValue = new Company.Communication.CompanyService.LoadRequest();
            inValue.Body = new Company.Communication.CompanyService.LoadRequestBody();
            Company.Communication.CompanyService.LoadResponse retVal = ((Company.Communication.CompanyService.CompanyServiceSoap)(this)).Load(inValue);
            return retVal.Body.LoadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Company.Communication.CompanyService.LoadResponse> Company.Communication.CompanyService.CompanyServiceSoap.LoadAsync(Company.Communication.CompanyService.LoadRequest request) {
            return base.Channel.LoadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Company.Communication.CompanyService.LoadResponse> LoadAsync() {
            Company.Communication.CompanyService.LoadRequest inValue = new Company.Communication.CompanyService.LoadRequest();
            inValue.Body = new Company.Communication.CompanyService.LoadRequestBody();
            return ((Company.Communication.CompanyService.CompanyServiceSoap)(this)).LoadAsync(inValue);
        }
    }
}
