//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phonebook.Communication.PhonebookService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        private bool LockedField;
        
        private Phonebook.Communication.PhonebookService.ContactCategory CategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Locked {
            get {
                return this.LockedField;
            }
            set {
                if ((this.LockedField.Equals(value) != true)) {
                    this.LockedField = value;
                    this.RaisePropertyChanged("Locked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public Phonebook.Communication.PhonebookService.ContactCategory Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactCategory", Namespace="http://tempuri.org/")]
    public enum ContactCategory : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        General = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Personal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Working = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhonebookService.PhonebookServiceSoap")]
    public interface PhonebookServiceSoap {
        
        // CODEGEN: Generating message contract since element name LoadResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Load", ReplyAction="*")]
        Phonebook.Communication.PhonebookService.LoadResponse Load(Phonebook.Communication.PhonebookService.LoadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Load", ReplyAction="*")]
        System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.LoadResponse> LoadAsync(Phonebook.Communication.PhonebookService.LoadRequest request);
        
        // CODEGEN: Generating message contract since element name contact from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        Phonebook.Communication.PhonebookService.AddResponse Add(Phonebook.Communication.PhonebookService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.AddResponse> AddAsync(Phonebook.Communication.PhonebookService.AddRequest request);
        
        // CODEGEN: Generating message contract since element name contact from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        Phonebook.Communication.PhonebookService.RemoveResponse Remove(Phonebook.Communication.PhonebookService.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.RemoveResponse> RemoveAsync(Phonebook.Communication.PhonebookService.RemoveRequest request);
        
        // CODEGEN: Generating message contract since element name contact from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        Phonebook.Communication.PhonebookService.UpdateResponse Update(Phonebook.Communication.PhonebookService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.UpdateResponse> UpdateAsync(Phonebook.Communication.PhonebookService.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Load", Namespace="http://tempuri.org/", Order=0)]
        public Phonebook.Communication.PhonebookService.LoadRequestBody Body;
        
        public LoadRequest() {
        }
        
        public LoadRequest(Phonebook.Communication.PhonebookService.LoadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadRequestBody {
        
        public LoadRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadResponse", Namespace="http://tempuri.org/", Order=0)]
        public Phonebook.Communication.PhonebookService.LoadResponseBody Body;
        
        public LoadResponse() {
        }
        
        public LoadResponse(Phonebook.Communication.PhonebookService.LoadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Phonebook.Communication.PhonebookService.Contact[] LoadResult;
        
        public LoadResponseBody() {
        }
        
        public LoadResponseBody(Phonebook.Communication.PhonebookService.Contact[] LoadResult) {
            this.LoadResult = LoadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public Phonebook.Communication.PhonebookService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(Phonebook.Communication.PhonebookService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Phonebook.Communication.PhonebookService.Contact contact;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(Phonebook.Communication.PhonebookService.Contact contact) {
            this.contact = contact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public Phonebook.Communication.PhonebookService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(Phonebook.Communication.PhonebookService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(int AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://tempuri.org/", Order=0)]
        public Phonebook.Communication.PhonebookService.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(Phonebook.Communication.PhonebookService.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Phonebook.Communication.PhonebookService.Contact contact;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(Phonebook.Communication.PhonebookService.Contact contact) {
            this.contact = contact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Phonebook.Communication.PhonebookService.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(Phonebook.Communication.PhonebookService.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(int RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public Phonebook.Communication.PhonebookService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Phonebook.Communication.PhonebookService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Phonebook.Communication.PhonebookService.Contact contact;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(Phonebook.Communication.PhonebookService.Contact contact) {
            this.contact = contact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Phonebook.Communication.PhonebookService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(Phonebook.Communication.PhonebookService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(int UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PhonebookServiceSoapChannel : Phonebook.Communication.PhonebookService.PhonebookServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhonebookServiceSoapClient : System.ServiceModel.ClientBase<Phonebook.Communication.PhonebookService.PhonebookServiceSoap>, Phonebook.Communication.PhonebookService.PhonebookServiceSoap {
        
        public PhonebookServiceSoapClient() {
        }
        
        public PhonebookServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhonebookServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhonebookServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhonebookServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Phonebook.Communication.PhonebookService.LoadResponse Phonebook.Communication.PhonebookService.PhonebookServiceSoap.Load(Phonebook.Communication.PhonebookService.LoadRequest request) {
            return base.Channel.Load(request);
        }
        
        public Phonebook.Communication.PhonebookService.Contact[] Load() {
            Phonebook.Communication.PhonebookService.LoadRequest inValue = new Phonebook.Communication.PhonebookService.LoadRequest();
            inValue.Body = new Phonebook.Communication.PhonebookService.LoadRequestBody();
            Phonebook.Communication.PhonebookService.LoadResponse retVal = ((Phonebook.Communication.PhonebookService.PhonebookServiceSoap)(this)).Load(inValue);
            return retVal.Body.LoadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.LoadResponse> Phonebook.Communication.PhonebookService.PhonebookServiceSoap.LoadAsync(Phonebook.Communication.PhonebookService.LoadRequest request) {
            return base.Channel.LoadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.LoadResponse> LoadAsync() {
            Phonebook.Communication.PhonebookService.LoadRequest inValue = new Phonebook.Communication.PhonebookService.LoadRequest();
            inValue.Body = new Phonebook.Communication.PhonebookService.LoadRequestBody();
            return ((Phonebook.Communication.PhonebookService.PhonebookServiceSoap)(this)).LoadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Phonebook.Communication.PhonebookService.AddResponse Phonebook.Communication.PhonebookService.PhonebookServiceSoap.Add(Phonebook.Communication.PhonebookService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public int Add(Phonebook.Communication.PhonebookService.Contact contact) {
            Phonebook.Communication.PhonebookService.AddRequest inValue = new Phonebook.Communication.PhonebookService.AddRequest();
            inValue.Body = new Phonebook.Communication.PhonebookService.AddRequestBody();
            inValue.Body.contact = contact;
            Phonebook.Communication.PhonebookService.AddResponse retVal = ((Phonebook.Communication.PhonebookService.PhonebookServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.AddResponse> Phonebook.Communication.PhonebookService.PhonebookServiceSoap.AddAsync(Phonebook.Communication.PhonebookService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.AddResponse> AddAsync(Phonebook.Communication.PhonebookService.Contact contact) {
            Phonebook.Communication.PhonebookService.AddRequest inValue = new Phonebook.Communication.PhonebookService.AddRequest();
            inValue.Body = new Phonebook.Communication.PhonebookService.AddRequestBody();
            inValue.Body.contact = contact;
            return ((Phonebook.Communication.PhonebookService.PhonebookServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Phonebook.Communication.PhonebookService.RemoveResponse Phonebook.Communication.PhonebookService.PhonebookServiceSoap.Remove(Phonebook.Communication.PhonebookService.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public int Remove(Phonebook.Communication.PhonebookService.Contact contact) {
            Phonebook.Communication.PhonebookService.RemoveRequest inValue = new Phonebook.Communication.PhonebookService.RemoveRequest();
            inValue.Body = new Phonebook.Communication.PhonebookService.RemoveRequestBody();
            inValue.Body.contact = contact;
            Phonebook.Communication.PhonebookService.RemoveResponse retVal = ((Phonebook.Communication.PhonebookService.PhonebookServiceSoap)(this)).Remove(inValue);
            return retVal.Body.RemoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.RemoveResponse> Phonebook.Communication.PhonebookService.PhonebookServiceSoap.RemoveAsync(Phonebook.Communication.PhonebookService.RemoveRequest request) {
            return base.Channel.RemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.RemoveResponse> RemoveAsync(Phonebook.Communication.PhonebookService.Contact contact) {
            Phonebook.Communication.PhonebookService.RemoveRequest inValue = new Phonebook.Communication.PhonebookService.RemoveRequest();
            inValue.Body = new Phonebook.Communication.PhonebookService.RemoveRequestBody();
            inValue.Body.contact = contact;
            return ((Phonebook.Communication.PhonebookService.PhonebookServiceSoap)(this)).RemoveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Phonebook.Communication.PhonebookService.UpdateResponse Phonebook.Communication.PhonebookService.PhonebookServiceSoap.Update(Phonebook.Communication.PhonebookService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public int Update(Phonebook.Communication.PhonebookService.Contact contact) {
            Phonebook.Communication.PhonebookService.UpdateRequest inValue = new Phonebook.Communication.PhonebookService.UpdateRequest();
            inValue.Body = new Phonebook.Communication.PhonebookService.UpdateRequestBody();
            inValue.Body.contact = contact;
            Phonebook.Communication.PhonebookService.UpdateResponse retVal = ((Phonebook.Communication.PhonebookService.PhonebookServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.UpdateResponse> Phonebook.Communication.PhonebookService.PhonebookServiceSoap.UpdateAsync(Phonebook.Communication.PhonebookService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Phonebook.Communication.PhonebookService.UpdateResponse> UpdateAsync(Phonebook.Communication.PhonebookService.Contact contact) {
            Phonebook.Communication.PhonebookService.UpdateRequest inValue = new Phonebook.Communication.PhonebookService.UpdateRequest();
            inValue.Body = new Phonebook.Communication.PhonebookService.UpdateRequestBody();
            inValue.Body.contact = contact;
            return ((Phonebook.Communication.PhonebookService.PhonebookServiceSoap)(this)).UpdateAsync(inValue);
        }
    }
}
